export const pairs: string[] = [
    'BTCUSDT', 
    'ETHUSDT', 
    'SOLUSDT',
    'AVAXUSDT',
    'TRXUSDT',
    'XRPUSDT',
    'ADAUSDT',
    'LINKUSDT',
    'MATICUSDT',
    'DOTUSDT',
    'RNDRUSDT',
    'LTCUSDT',
    'BCHUSDT',
]